//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/NSW_CSC_Input/NSW_CSC_InputKeymap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NSW_CSC_InputKeymap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NSW_CSC_InputKeymap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NSW_CSC_InputKeymap"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""d77020cb-b147-40fb-a81b-eb101517794c"",
            ""actions"": [
                {
                    ""name"": ""Walk/Run"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e8298e6f-d478-4253-9ebb-832b4ae885f2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""14f51803-72be-434e-9773-fbfc0547776a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6f236904-4b27-4c5b-b1c5-0bed3e18ef1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2321a18b-e3e2-4082-980b-bdbd5ac1c6f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""40c0cfb3-3c51-41a2-9a56-d37862cebc9e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemRelease"",
                    ""type"": ""Button"",
                    ""id"": ""ec1a9a4b-db67-4856-bca8-adbefeb24596"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionOne"",
                    ""type"": ""Button"",
                    ""id"": ""389d2526-6391-4ebf-9ed2-7d424b8d412e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionTwo"",
                    ""type"": ""Button"",
                    ""id"": ""55a57770-d1e6-41f1-b930-b4aa2c2fee22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionThree"",
                    ""type"": ""Button"",
                    ""id"": ""0f800d39-fb0d-456a-a608-1051f45e9ae2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionFour"",
                    ""type"": ""Button"",
                    ""id"": ""0ce2594c-b1ab-4b4b-90da-5c8ad26c34e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Console"",
                    ""type"": ""Button"",
                    ""id"": ""a855fb0e-d836-415a-82ab-28240c1a5120"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SendCommandlet"",
                    ""type"": ""Button"",
                    ""id"": ""333f788e-acb6-4eef-8586-5c97177ddc5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c28a5cc-9752-41c6-81ca-33c7c99247bb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e46972ef-4406-4981-916f-2263cb3c0ee1"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91e26e51-ba19-4de3-8d99-b1faca496e9c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71411661-93a5-4a16-99e2-1fa5ade7b816"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cc8cfa3-c43e-4a33-af30-2357bea545e3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf3da53-b732-41a9-b1c4-a1997fb3aff6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc36a469-c0e3-4149-bf6f-96a9fca66211"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79aa87b9-ed91-4087-937e-04845641d345"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e195a35c-9994-41a4-91f7-0032f2204a9d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc7ee1ea-e7c5-46d5-9493-144cb7152f54"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""78bb7feb-5082-460a-a8ae-febadadb6fac"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1ca95518-e2f7-4767-a157-fc1562fb0c69"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""752ded74-44a4-473a-89dc-84fd1f2b0f00"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9495dd33-fc34-437c-a85d-23a9ebdaaddf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3c5dfe26-6585-4161-bde5-6472891d71ca"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk/Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9095c979-e4aa-4a28-909c-91e14a31c836"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5237dcee-540a-4f6b-a76b-e1a616eaa5b9"",
                    ""path"": ""<Keyboard>/#(1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06db17c0-7391-49f9-a411-c82fb7a5fc7e"",
                    ""path"": ""<Keyboard>/#(2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efc81594-cc5f-42ca-91c3-912460752959"",
                    ""path"": ""<Keyboard>/#(3)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d40e3cc-7b70-45f1-8f4e-d74d8f5cc50d"",
                    ""path"": ""<Keyboard>/#(4)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e063a621-f730-4a19-99bb-9787979e1438"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Console"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dd6e1e5-3d70-4673-bf07-1a3d01ac5d0b"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SendCommandlet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_WalkRun = m_PlayerControls.FindAction("Walk/Run", throwIfNotFound: true);
        m_PlayerControls_Crouch = m_PlayerControls.FindAction("Crouch", throwIfNotFound: true);
        m_PlayerControls_Jump = m_PlayerControls.FindAction("Jump", throwIfNotFound: true);
        m_PlayerControls_Run = m_PlayerControls.FindAction("Run", throwIfNotFound: true);
        m_PlayerControls_Camera = m_PlayerControls.FindAction("Camera", throwIfNotFound: true);
        m_PlayerControls_ItemRelease = m_PlayerControls.FindAction("ItemRelease", throwIfNotFound: true);
        m_PlayerControls_ActionOne = m_PlayerControls.FindAction("ActionOne", throwIfNotFound: true);
        m_PlayerControls_ActionTwo = m_PlayerControls.FindAction("ActionTwo", throwIfNotFound: true);
        m_PlayerControls_ActionThree = m_PlayerControls.FindAction("ActionThree", throwIfNotFound: true);
        m_PlayerControls_ActionFour = m_PlayerControls.FindAction("ActionFour", throwIfNotFound: true);
        m_PlayerControls_Console = m_PlayerControls.FindAction("Console", throwIfNotFound: true);
        m_PlayerControls_SendCommandlet = m_PlayerControls.FindAction("SendCommandlet", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private List<IPlayerControlsActions> m_PlayerControlsActionsCallbackInterfaces = new List<IPlayerControlsActions>();
    private readonly InputAction m_PlayerControls_WalkRun;
    private readonly InputAction m_PlayerControls_Crouch;
    private readonly InputAction m_PlayerControls_Jump;
    private readonly InputAction m_PlayerControls_Run;
    private readonly InputAction m_PlayerControls_Camera;
    private readonly InputAction m_PlayerControls_ItemRelease;
    private readonly InputAction m_PlayerControls_ActionOne;
    private readonly InputAction m_PlayerControls_ActionTwo;
    private readonly InputAction m_PlayerControls_ActionThree;
    private readonly InputAction m_PlayerControls_ActionFour;
    private readonly InputAction m_PlayerControls_Console;
    private readonly InputAction m_PlayerControls_SendCommandlet;
    public struct PlayerControlsActions
    {
        private @NSW_CSC_InputKeymap m_Wrapper;
        public PlayerControlsActions(@NSW_CSC_InputKeymap wrapper) { m_Wrapper = wrapper; }
        public InputAction @WalkRun => m_Wrapper.m_PlayerControls_WalkRun;
        public InputAction @Crouch => m_Wrapper.m_PlayerControls_Crouch;
        public InputAction @Jump => m_Wrapper.m_PlayerControls_Jump;
        public InputAction @Run => m_Wrapper.m_PlayerControls_Run;
        public InputAction @Camera => m_Wrapper.m_PlayerControls_Camera;
        public InputAction @ItemRelease => m_Wrapper.m_PlayerControls_ItemRelease;
        public InputAction @ActionOne => m_Wrapper.m_PlayerControls_ActionOne;
        public InputAction @ActionTwo => m_Wrapper.m_PlayerControls_ActionTwo;
        public InputAction @ActionThree => m_Wrapper.m_PlayerControls_ActionThree;
        public InputAction @ActionFour => m_Wrapper.m_PlayerControls_ActionFour;
        public InputAction @Console => m_Wrapper.m_PlayerControls_Console;
        public InputAction @SendCommandlet => m_Wrapper.m_PlayerControls_SendCommandlet;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Add(instance);
            @WalkRun.started += instance.OnWalkRun;
            @WalkRun.performed += instance.OnWalkRun;
            @WalkRun.canceled += instance.OnWalkRun;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @ItemRelease.started += instance.OnItemRelease;
            @ItemRelease.performed += instance.OnItemRelease;
            @ItemRelease.canceled += instance.OnItemRelease;
            @ActionOne.started += instance.OnActionOne;
            @ActionOne.performed += instance.OnActionOne;
            @ActionOne.canceled += instance.OnActionOne;
            @ActionTwo.started += instance.OnActionTwo;
            @ActionTwo.performed += instance.OnActionTwo;
            @ActionTwo.canceled += instance.OnActionTwo;
            @ActionThree.started += instance.OnActionThree;
            @ActionThree.performed += instance.OnActionThree;
            @ActionThree.canceled += instance.OnActionThree;
            @ActionFour.started += instance.OnActionFour;
            @ActionFour.performed += instance.OnActionFour;
            @ActionFour.canceled += instance.OnActionFour;
            @Console.started += instance.OnConsole;
            @Console.performed += instance.OnConsole;
            @Console.canceled += instance.OnConsole;
            @SendCommandlet.started += instance.OnSendCommandlet;
            @SendCommandlet.performed += instance.OnSendCommandlet;
            @SendCommandlet.canceled += instance.OnSendCommandlet;
        }

        private void UnregisterCallbacks(IPlayerControlsActions instance)
        {
            @WalkRun.started -= instance.OnWalkRun;
            @WalkRun.performed -= instance.OnWalkRun;
            @WalkRun.canceled -= instance.OnWalkRun;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @ItemRelease.started -= instance.OnItemRelease;
            @ItemRelease.performed -= instance.OnItemRelease;
            @ItemRelease.canceled -= instance.OnItemRelease;
            @ActionOne.started -= instance.OnActionOne;
            @ActionOne.performed -= instance.OnActionOne;
            @ActionOne.canceled -= instance.OnActionOne;
            @ActionTwo.started -= instance.OnActionTwo;
            @ActionTwo.performed -= instance.OnActionTwo;
            @ActionTwo.canceled -= instance.OnActionTwo;
            @ActionThree.started -= instance.OnActionThree;
            @ActionThree.performed -= instance.OnActionThree;
            @ActionThree.canceled -= instance.OnActionThree;
            @ActionFour.started -= instance.OnActionFour;
            @ActionFour.performed -= instance.OnActionFour;
            @ActionFour.canceled -= instance.OnActionFour;
            @Console.started -= instance.OnConsole;
            @Console.performed -= instance.OnConsole;
            @Console.canceled -= instance.OnConsole;
            @SendCommandlet.started -= instance.OnSendCommandlet;
            @SendCommandlet.performed -= instance.OnSendCommandlet;
            @SendCommandlet.canceled -= instance.OnSendCommandlet;
        }

        public void RemoveCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);
    public interface IPlayerControlsActions
    {
        void OnWalkRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnItemRelease(InputAction.CallbackContext context);
        void OnActionOne(InputAction.CallbackContext context);
        void OnActionTwo(InputAction.CallbackContext context);
        void OnActionThree(InputAction.CallbackContext context);
        void OnActionFour(InputAction.CallbackContext context);
        void OnConsole(InputAction.CallbackContext context);
        void OnSendCommandlet(InputAction.CallbackContext context);
    }
}
